### ISSUE TITLE
No sending possible, After successfully resolving Captcha , the field is "EMPTY"

### ISSUE THREAD

**Issue by RoyalPulp** [3Dgoo/silverstripe-hcaptcha#5]
Hi there!

This module / the captcha is not working correctly, but I don't know, if it's the module or the hCaptcha service

I implemented it on various SilverStripe 5.1.1 installations,  
After successfully resolving the captcha, and pushing the "send" button, I get the "EMPTY" Message: "Please answer the captcha. If you do not see the captcha please enable Javascript"

I hope anybody has an idea, what could be the reason behind this

try it on: https://demo.spring-info.de/kontakt

Thanks, Hendrik

**Comment by RoyalPulp** [comment]
Hello - I still have this problem - HCaptcha Module is not usable like this!
Anyone?

**Comment by 3Dgoo** [comment]
Hello,

Thank you for flagging this issue.
I have not had a chance to check this yet. If you downgrade Silverstripe to 5.0 does it work? I am trying to work out if this broke from a Silverstripe 5.1 change or if it might be something else.

**Comment by 3Dgoo** [comment]
Also, what version of PHP are you running?

**Comment by RoyalPulp** [comment]
I just downgraded to SilverStripe 5.0.23 but the form isnt submitted

I use PHP 8.1

**Comment by 3Dgoo** [comment]
I just tested this in Silverstripe 4.11 on PHP 8.1, with code that was previously working. I have not changed anything and this is no longer working either. Interesting. Perhaps something in the Captcha API has changed.

**Comment by 3Dgoo** [comment]
Hmmm, my failed test was on a local copy.
I tested the same code on the production site and it sent correctly.

**Comment by 3Dgoo** [comment]
Silly me:

> Adding hostnames that don't resolve or resolve to localhost will not work.

I will try upgrading the site to 5.0 and see if the issue still occurs on the live site.

**Comment by 3Dgoo** [comment]
I have now tested this on Silverstripe 5.1 with PHP 8.1 on a production site and this worked correctly.

Perhaps check the API key has the domain is set correctly?
Otherwise, check the logs to see if there are any other details on what is going wrong.

**Comment by RoyalPulp** [comment]
Really Strange, my API key is correct. the website had been using the oposs hcaptcha module for over a year, swithced to this module a short time ago, when upgrading to SilverStripe 5

I have over 15 SilverStripe websites that use this SilverStripe hCaptcha module  - most of them do work and a few don't - I try to find out, what's the difference

It looks like: All websites that fail to work are on the same Host! There is one on this host that works with hCaptcha, but it uses silverstripe 4 and the oposs/silverstripe-hcaptcha module

**Comment by 3Dgoo** [comment]
I have been looking through the code. I can see a couple of things that might be the issue.

1. The server request that gets sent contains the server IP in the data payload. 
```'remoteip' => rawurlencode($_SERVER['REMOTE_ADDR']),```
The IP might be getting flagged by the Captcha API. I will try removing this (possibly with an optional config variable to enable it, or maybe completely)

2. The request gets sent as a get request. There is a chance this could be truncating the data if it is too long. This would be better as a post request.

I will look at creating a feature branch with these changes. Once they are ready, are you happy to test the feature branch on your test site to confirm this fixes the problem?

**Comment by 3Dgoo** [comment]
I have created a pull request for this. 

Can you please use the `feature/server-ip-fix` branch on your test site to test that this works and it fixes the issue for you?

If it does, I will merge this into master / 2.x and do a release with this fix.

**Comment by RoyalPulp** [comment]
Okay, thanks!! I tried the feature/server-ip-fix version  in one of the projects where it used to fail  -> It works now !!

**Comment by 3Dgoo** [comment]
Great. I will merge this in. Thank you for flagging this and helping to solve the problem.

**Comment by 3Dgoo** [comment]
I have merged this in and released it on the 2.x branch as well as with release 2.0.1.

I have also added a language config variable so we can set the language of the hCaptcha if we like. Feel free to give it a try:

```
X3dgoo\HCaptcha\Forms\HCaptchaField:
  language_code: "de"
```

**Comment by RoyalPulp** [comment]
For single-language Websites thats great, but all multilanguage websites need more than one locale . I found a bit of code, an Extension for the othe HCaptchaField Module, that I modified to work with this module. This switches the HCaptcha-Locale by current fluent-locale.

**Comment by 3Dgoo** [comment]
I have updated the code again (#9) to use the current locale. Let me know if this does not work. Or if you notice any other issues.
